/**
 * Guardian Monitor - GP Referral Template
 */

function addLabelValue(doc, label, value) {
  doc
    .font('Helvetica-Bold')
    .text(`${label}: `, { continued: true });

  doc
    .font('Helvetica')
    .text(value);
}

function addSectionHeading(doc, heading) {
  doc.moveDown(0.8);

  doc
    .font('Helvetica-Bold')
    .fontSize(11)
    .text(heading);

  doc.moveDown(0.3);
}

function renderReferralTemplate(doc, data) {
  const {
    referralDate,
    specialist,
    patient,
    clinicalDetails,
    investigations,
    reasonForReferral,
    referringDoctor
  } = data;

  // Main title
  doc
    .font('Helvetica-Bold')
    .fontSize(18)
    .text('Doctor Referral', {
      align: 'center'
    });

  doc.moveDown(1.5);

  // Date
  doc
    .font('Helvetica')
    .fontSize(10)
    .text(referralDate, {
      align: 'right'
    });

  doc.moveDown();

  // Recipient details
  doc
    .font('Helvetica-Bold')
    .text('To:');

  doc
    .font('Helvetica')
    .text(specialist.name)
    .text(`${specialist.department}, ${specialist.hospital}`)
    .text(specialist.addressLine1);

  if (specialist.addressLine2) {
    doc.text(specialist.addressLine2);
  }

  doc.moveDown();

  doc.text(
    `Dear ${specialist.salutation || specialist.name},`
  );

  doc.moveDown();

  // Patient reference
  doc
    .font('Helvetica-Bold')
    .text(
      `Re: Referral for ${patient.name}, Date of Birth: ${patient.dateOfBirth}`
    );

  doc.moveDown();

  doc
    .font('Helvetica')
    .text(
      `I am referring ${patient.name} to your clinic for further evaluation and management of ${clinicalDetails.presentingComplaint}.`,
      {
        align: 'justify'
      }
    );

  // Clinical Details
  addSectionHeading(doc, 'Clinical Details');

  addLabelValue(
    doc,
    'Presenting Complaint',
    clinicalDetails.presentingComplaint
  );

  addLabelValue(
    doc,
    'Duration',
    clinicalDetails.duration
  );

  addLabelValue(
    doc,
    'Relevant Findings',
    clinicalDetails.relevantFindings
  );

  addLabelValue(
    doc,
    'Past Medical History',
    clinicalDetails.pastMedicalHistory
  );

  addLabelValue(
    doc,
    'Current Medications',
    clinicalDetails.currentMedications
  );

  // Investigations
  addSectionHeading(doc, 'Investigations');

  addLabelValue(
    doc,
    'Recent Tests',
    investigations.recentTests
  );

  addLabelValue(
    doc,
    'Results',
    investigations.results
  );

  // Referral reason
  addSectionHeading(doc, 'Reason for Referral');

  doc
    .font('Helvetica')
    .text(reasonForReferral, {
      align: 'justify'
    });

  // Contact information
  addSectionHeading(
    doc,
    "Patient's Contact Information"
  );

  addLabelValue(
    doc,
    'Phone Number',
    patient.phone
  );

  addLabelValue(
    doc,
    'Email Address',
    patient.email
  );

  doc.moveDown();

  doc.text(
    'Enclosed are relevant test results and imaging reports for your review. Please do not hesitate to contact me if you require further information.',
    {
      align: 'justify'
    }
  );

  doc.moveDown();

  doc.text(
    'Thank you for your attention to this referral. I look forward to your evaluation and recommendations.',
    {
      align: 'justify'
    }
  );

  // Signature
  doc.moveDown(1.2);

  doc.text('Yours sincerely,');

  doc.moveDown(1.2);

  doc
    .font('Helvetica-Bold')
    .text(referringDoctor.name);

  doc
    .font('Helvetica')
    .text(referringDoctor.title)
    .text(referringDoctor.phone)
    .text(referringDoctor.clinic);

  // Footer
  doc.moveDown(1.5);

  doc
    .fontSize(8)
    .fillColor('grey')
    .text(
      'Generated by Guardian Monitor',
      {
        align: 'center'
      }
    );
}

module.exports = {
  renderReferralTemplate
};