const mongoose = require('mongoose');

// This is deliberately separate from DailyReport, which is a per-patient
// caretaker observation.  A DailyOperationalReport is the organisation-wide
// operational PDF generated by the daily-report API.
const DailyOperationalReportSchema = new mongoose.Schema({
  reportDate: { type: Date, required: true, index: true },
  generatedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  signoffName: { type: String, required: true },
  signedOffAt: { type: Date, required: true },
  generalNotes: { type: String, required: true },
  analytics: { type: String, required: true },
  metrics: { type: mongoose.Schema.Types.Mixed, required: true },
  comparison: { type: mongoose.Schema.Types.Mixed, required: true },
  fileName: { type: String, required: true, unique: true },
  filePath: { type: String, required: true },
  createdAt: { type: Date, default: Date.now }
});

DailyOperationalReportSchema.index({ reportDate: -1, createdAt: -1 });

module.exports = mongoose.model('DailyOperationalReport', DailyOperationalReportSchema);
