name: Run Node.js Application

on:
  push:
    branches:
      - '*deploy' # Trigger only on branches ending with 'deploy'

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # Match your desired Node.js version

    - name: Install dependencies
      run: npm install # Ensures creation of package-lock.json

    - name: Install dependencies
      run: npm ci # Ensures clean installation of dependencies

    - name: Start the application
      env:
        MONGODB_URI: "mongodb://mongo:ugvNlAxTEDizUfJSDtruCJJWMZNQvJLt@hopper.proxy.rlwy.net:30442" # Unsafe and should not be hardcoded in VCS
      run: node src/server.js
